---
title: "Survival Assessment"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: readable
    logo: www/Eversana_Logo_H_RGB.png
    vertical_layout: fill
runtime: shiny
css: style.css
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(plotly)

library(shinyWidgets)
library(colourpicker)
library(shinypop)
library(sortable)

use_noty()

scripts <- list.files(here::here("R"))
devtools::load_all()

```


Results
=============================================================
    
Row {data-height=900,  .tabset .tabset-fade}
-------------------------------------
    
### Kaplan-Meier
This is a slide that covers all outcomes/analyses    
```{r}
test <- shiny::eventReactive(input$sim.dat,

    {

     dat <- .simsurv(150, "max")
     fits <- .test.ph.aft(test()$dat)
     
      })

test2 <- shiny::eventReactive(input$sim.dat,

    {


      })

 


  
  output$plot <- shiny::renderTable(tests2()$fits)
  

    


  shiny::fillCol(flex = c(1,6,1),

   shinyWidgets::dropdown(label = "Settings and export", icon = icon("gear"),
                          animate = animateOptions(
      enter = animations$fading_entrances$fadeInLeftBig,
      exit = animations$fading_exits$fadeOutLeftBig
    ),
    shiny::actionButton("km.plot", "Plot KM")
     
    
    
  #   selectInput(
  #     "layout",
  #     "Layout Algorithm",
  #     choices = layouts,
  #     selected = "kamadakawai"
  #   ),
  #   numericInput(
  #     "text_size",
  #     "Treatment text size",
  #     min = 1,
  #     max = 100,
  #     value = 3
  #   ),
  #   numericInput(
  #     "list_size",
  #     "Study name text size",
  #     min = 1,
  #     max = 100,
  #     value = 4),
  #   
  #   colourpicker::colourInput("fp_col", value = "#002351", label = "Node colour"),
  #   
  #   hr(),
  # 
  #   shiny::actionButton("add_fp", label = "Add to downloads"),
  #   
  #   numericInput(
  #     "dl_width",
  #     "Download width",
  #     min = 1,
  #     max = 100,
  #     value = 15
  #   ),
  #   numericInput(
  #     "dl_height",
  #     "Download height",
  #     min = 1,
  #     max = 100,
  #     value = 10
  #   ) 
  ),
  
   shiny::tableOutput("plot")
 
  )

```

### Cumulative Hazard Plots
    
```{r echo = FALSE, warning = FALSE, message = FALSE}
type <- "cont_arm" 

layouts <- c("adj",
"circle",
"circrand",
"eigen",
"fruchtermanreingold",
"geodist",
"hall",
"kamadakawai",
"mds",
"princoord",
"random",
"rmds",
"segeo",
"seham",
"target")



#dat_slr <- crgnma::fn_BUGStoSLR(dat_in, dat_trts, outcome_type = "cont_arm")

test <- reactive({
# fn_network(raw_WinBUGS = dat_slr,
#                          treatment_list = dat_trts,
#                          add_study_list = TRUE,
#                          graph_marg = c(1, 1, 1, 1),
#                          title_marg = c(0, 0, 0, 0),
#                          list_size = input$list_size,
#                          text_size = input$text_size,
#                          min_node_size_factor = 15,
#                          max_node_size_factor = 40,
#                          outcome_name = "temp",
#                          outcome_type = type,
#                          alg = input$layout,
#                          node_colour = input$fp_col
#   )

})

  
  
  


observeEvent(input$add_fp, {
 
  
  outs$fp <- test()$plot
  
  
  noty("Added network plot to downloads", type = "success", layout = "bottom")
   #showNotification("Added to downloads")
  
})


```
   
### QQ Plots
    
```{r}
```
   
### Parametric Fits
    
```{r}
```
   
### Schoenfeld residuals test and plot
    
```{r}
```

### Smoothed Hazards
    
```{r}
```


Methods + Resources
======================================================================

Row {data-height=1000,  .tabset .tabset-fade}
-------------------------------------

### Overview


Sidebar {.sidebar data-width=300}
======================================================================

Simulate Data and Submit a Guess


```{r}

hr()

br()
shiny::numericInput("n.sim", 
                   min = 100,
                   max = 10000,
                   value = 150,
                   step = 25,
                   label = "Number of patients")

br()
shiny::selectInput("mat", label = "Maturity of Data",
                   choices = c("Low" = "low", 
                               "Moderate" = "mod", 
                               "Max" = "max"),
                   selected = "Max")
br()
shiny::fillRow(shiny::actionButton("sim.dat", label = "Simulate Data")) 

br()
br()
hr()
br()
shiny::selectInput("deliv_sel", label = "Deliverable",
                   choices = c("Global", "UK", "France"),
                   selected = "Global")

shiny::selectInput("sg_sel", label = "Guess for distribution",
                   choices = c("Mixed", "Bio-naive", "Bio-experienced"),
                   selected = "Mixed")

shiny::selectInput("outcome_sel", label = "Guess for whether PH/AFT is satisfied",
                   choices = c("ACR 20", "ACR 50", "ACR 70"),
                   selected = "ACR 20")

hr()

shiny::fillRow(shiny::actionButton("dl_all", label = "Make Guess")) 



output$dl_all <-  downloadHandler(
  filename = "test.pptx",
  content =function(file){
    
    file_pptx <- tempfile(fileext = ".pptx")
      
    set.seed(0)
    
    gen_pptx(rvg::dml(ggobj = outs$fp), file_pptx, width = input$dl_width, height = input$dl_height)
      file.rename( from = file_pptx, to = file )
     
    #    ggsave(filename = file,plot= test()$plot, device = "svg")
    }
)

br()
br()





output$export_list <- renderUI({
  
  sortable::bucket_list(
    header = "Manage/Sort export",
    sortable::add_rank_list(
      text = "Included",
      labels = names(outs),
      options = sortable_options(multiDrag = TRUE)
    ),
    sortable::add_rank_list(
      text = "Excluded",
      labels = NULL,
      options = sortable_options(multiDrag = TRUE)
    )
  )
})


```


